[package]
name = "rtriangulate"
version = "0.1.0"
authors = ["Samuel Loretan <tynril@gmail.com>"]

[dependencies]

[dev-dependencies]
bencher = "0.1.2"

[[bench]]
name = "triangulate"
harness = false

[lib]
name = "rtriangulate"
path = "src/lib.rs"
